Repository revue-org/revue, pull requests merged in 2024-02, with the labels that each got.

#35 feature/camera-enabling
  camera/src/producer.ts
  domain/src/domain/device/core/impl/CameraImpl.ts
  domain/src/domain/device/core/impl/SensorImpl.ts
  domain/src/domain/device/factories/DeviceFactory.ts
  domain/src/domain/device/factories/impl/DeviceFactoryImpl.ts
  domain/src/storage/device/DeviceRepositoryImpl.ts
  domain/src/storage/device/schemas/CameraSchema.js
  domain/src/storage/device/schemas/SensorSchema.js
  frontend/src/components/devices/DeviceBadge.vue
  frontend/src/scripts/presentation/device/ComposeDevice.ts
  monitoring/db/device-init.js
  monitoring/src/controller/device.ts
  monitoring/src/routes/device.ts
  sensor/src/producer.ts
Labels: enhancement

#36 Refactor charts in frontend, link right creator id to new security rules
  auth/db/auth-init.js
  auth/src/controller/userAccess.ts
  frontend/src/components/devices/SensorData.vue
  frontend/src/components/security-rule/NewSecurityRulePopup.vue
  frontend/src/stores/buffers.ts
  frontend/src/stores/user.ts
  frontend/src/views/LoginView.vue
  monitoring/db/device-init.js
  monitoring/src/index.ts
  sensor/src/producer.ts
Labels: enhancement, frontend

#37 add popup for deletion
  frontend/src/components/devices/DeviceBadge.vue
  frontend/src/components/notification/NotificationBadge.vue
  frontend/src/components/security-rule/SecurityRuleBadge.vue
  frontend/src/scripts/Popups.ts
  frontend/src/stores/user.ts
  monitoring/src/routes/device.ts
Labels: chore

#40 refinements
  .env
  .github/workflows/build.yml
  .gitignore
  README.md
  alarm/Dockerfile
  alarm/package.json
  alarm/src/index.ts
  alarm/src/utils/JWTManager.ts
  alarm/test/anomaly/anomaly.get.test.ts
  alarm/vitest.config.mjs
  auth/Dockerfile
  auth/db/auth-init.js
  auth/package.json
  auth/src/index.ts
  auth/src/utils/JWTManager.ts
  auth/test/resources/userSample.ts
  auth/test/userAccess/newToken.test.ts
  auth/vitest.config.mjs
  camera/Dockerfile
  camera/docker-compose.yml
  camera/package.json
  camera/src/index.ts
  camera/src/producer.ts
  camera/src/utils/JWTManager.ts
  deploy.sh
  frontend/Dockerfile
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/devices/DeviceBadge.vue
  frontend/src/components/devices/NewDevicePopup.vue
  frontend/src/components/devices/SensorData.vue
  frontend/src/components/security-rule/NewSecurityRulePopup.vue
  frontend/src/components/security-rule/SecurityRuleBadge.vue
  frontend/src/components/security-rule/UpdateSecurityRulePopup.vue
  frontend/src/scripts/presentation/security-rule/ComposeSecurityRule.ts
  frontend/src/socket.ts
  frontend/src/utils/RequestHelper.ts
  frontend/src/views/LoginView.vue
  frontend/src/views/MonitoringView.vue
  frontend/src/views/SecurityRuleView.vue
  monitoring/Dockerfile
  monitoring/db/device-init.js
  monitoring/package.json
  monitoring/src/index.ts
  monitoring/src/utils/JWTManager.ts
  monitoring/test/resources/cameraSample.ts
  monitoring/test/resources/sensorSample.ts
  monitoring/vitest.config.mjs
  scripts/compose-all.sh
  scripts/compose-db.sh
  scripts/compose.sh
  sensor/Dockerfile
  sensor/docker-compose.yml
  sensor/package.json
  sensor/src/index.ts
  sensor/src/producer.ts
  sensor/src/utils/JWTManager.ts
  sensor/src/utils/RequestHelper.ts
  undeploy.sh
  update-version.sh
Labels: chore

#41 ASW Release
  alarm/src/utils/JWTManager.ts
  auth/src/controller/userAccess.ts
  auth/src/routes/userAccess.ts
  auth/src/utils/JWTManager.ts
  docs/report-asw/Relazione_Progetto_ASW.pdf
  docs/report-asw/main.tex
  docs/report-asw/out/main.pdf
  docs/report-asw/references.bib
  domain/src/storage/alarm-system/RecognizingNodeRepositoryImpl.ts
  frontend/src/components/devices/DeviceBadge.vue
  frontend/src/components/devices/NewDevicePopup.vue
  frontend/src/components/devices/SensorData.vue
  frontend/src/components/notification/NotificationBadge.vue
  frontend/src/components/security-rule/NewSecurityRulePopup.vue
  frontend/src/components/security-rule/SecurityRuleBadge.vue
  frontend/src/components/security-rule/UpdateSecurityRulePopup.vue
  frontend/src/socket.ts
  frontend/src/utils/RequestHelper.ts
  frontend/src/views/DevicesView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/MonitoringView.vue
  frontend/src/views/SecurityRuleView.vue
  monitoring/src/routes/device.ts
  monitoring/src/utils/JWTManager.ts
Labels: breaking change

#42 Add user for test
  README.md
  alarm/db/alarm-init.js
  auth/db/auth-init.js
Labels: breaking change

#44 Refactor commons files/functions
  alarm/src/controller/simulation.ts
  alarm/src/index.ts
  alarm/src/routes/anomaly.ts
  alarm/src/routes/notification.ts
  alarm/src/routes/recognizingNode.ts
  alarm/src/routes/securityRule.ts
  alarm/src/routes/simulation.ts
  alarm/src/utils/JWTManager.ts
  alarm/test/anomaly/anomaly.get.test.ts
  alarm/test/anomaly/anomaly.post.test.ts
  alarm/test/notification/notification.get.test.ts
  alarm/test/notification/notification.post.test.ts
  alarm/test/recognizingNode/recognizingNode.get.test.ts
  alarm/test/recognizingNode/recognizingNode.post.test.ts
  alarm/test/securityRule/securityRule.get.test.ts
  alarm/test/securityRule/securityRule.post.test.ts
  auth/src/index.ts
  auth/src/routes/user.ts
  auth/src/routes/userAccess.ts
  auth/src/utils/HttpStatusCode.ts
  auth/test/user/user.get.test.ts
  auth/test/user/user.post.test.ts
  auth/test/userAccess/login.test.ts
  auth/test/userAccess/logout.test.ts
  auth/test/userAccess/newToken.test.ts
  camera/package-lock.json
  camera/package.json
  camera/src/index.ts
  domain/src/utils/HttpStatusCode.ts
  domain/src/utils/connection.ts
  frontend/src/views/MonitoringView.vue
  monitoring/package-lock.json
  monitoring/src/index.ts
  monitoring/src/routes/device.ts
  monitoring/src/utils/HttpStatusCode.ts
  monitoring/src/utils/JWTManager.ts
  monitoring/test/device/device.delete.test.ts
  monitoring/test/device/device.get.test.ts
  monitoring/test/device/device.post.test.ts
  monitoring/test/device/device.put.test.ts
  package.json
  scripts/compose-service.sh
  scripts/compose.sh
Labels: refactor

#46 feature/sensor-alarm-triggering
  .github/workflows/build.yml
  alarm/db/alarm-init.js
  alarm/package-lock.json
  alarm/package.json
  alarm/src/consumer.ts
  alarm/src/controller/securityRule.ts
  alarm/src/index.ts
  alarm/src/utils/KafkaManager.ts
  alarm/src/utils/RequestHelper.ts
  alarm/test/resources/exceedingRuleSample.ts
  alarm/test/resources/intrusionRuleSample.ts
  auth/package-lock.json
  build.gradle.kts
  camera/package-lock.json
  domain/.dependency-cruiser.cjs
  domain/package-lock.json
  domain/package.json
  domain/src/application/security-rule/SecurityRuleService.ts
  domain/src/application/security-rule/impl/SecurityRuleServiceImpl.ts
  domain/src/domain/device/repositories/DeviceRepository.ts
  domain/src/storage/device/DeviceRepositoryImpl.ts
  domain/src/storage/security-rule/SecurityRuleRepositoryImpl.ts
  domain/src/storage/security-rule/schemas/ExceedingRuleSchema.js
  domain/src/storage/security-rule/schemas/IntrusionRuleSchema.js
  domain/test/security-rule/exceeding-rule.test.ts
  domain/test/setup.ts
  domain/tsconfig.json
  domain/vitest.config.d.mts
  domain/vitest.config.mjs
  frontend/package-lock.json
  log/package-lock.json
  log/src/consumer.ts
  monitoring/package-lock.json
  monitoring/src/consumer.ts
  monitoring/src/controller/device.ts
  monitoring/src/routes/device.ts
  monitoring/test/device/device.put.test.ts
  sensor/package-lock.json
  sensor/src/producer.ts
Labels: enhancement

#48 feature/frontend-history
  .env
  alarm/src/consumer.ts
  alarm/src/controller/anomaly.ts
  alarm/src/controller/notification.ts
  alarm/src/controller/recognizingNode.ts
  alarm/src/controller/securityRule.ts
  alarm/src/routes/notification.ts
  alarm/src/utils/RequestHelper.ts
  auth/src/controller/user.ts
  auth/src/controller/userAccess.ts
  domain/src/storage/anomaly/schemas/AnomalySchema.js
  domain/src/storage/device/EnvironmentDataRepositoryImpl.ts
  domain/src/storage/device/schemas/EnvironmentDataSchema.js
  domain/src/storage/security-rule/SecurityRuleRepositoryImpl.ts
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/history/EnvironmentDataBadge.vue
  frontend/src/components/history/IntrusionBadge.vue
  frontend/src/components/notification/NotificationBadge.vue
  frontend/src/components/security-rule/SecurityRuleBadge.vue
  frontend/src/router/index.ts
  frontend/src/scripts/presentation/device/ComposeEnvironmentData.ts
  frontend/src/scripts/presentation/security-rule/ComposeSecurityRule.ts
  frontend/src/utils/MeasureUtils.ts
  frontend/src/utils/RequestHelper.ts
  frontend/src/views/HistoryView.vue
  frontend/src/views/NotificationView.vue
  log/db/history-init.js
  log/docker-compose.yml
  log/src/consumer.ts
  log/src/controller/environmentData.ts
  log/src/routes/environmentData.ts
  log/src/utils/KafkaManager.ts
  monitoring/src/consumer.ts
  monitoring/src/controller/device.ts
  monitoring/src/utils/KafkaManager.ts
Labels: enhancement
