Repository revue-org/revue, pull requests merged in 2024-07, with the labels that each got.

#80 docs: align docs (api, uml, report)
  docs/api/asyncapi/specification.yml
  docs/api/openapi/alarm/specification.yml
  docs/api/openapi/auth/specification.yml
  docs/api/openapi/device/schemas.yml
  docs/api/openapi/device/specification.yml
  docs/api/openapi/location/specification.yml
  docs/api/openapi/monitoring/schemas.yml
  docs/api/openapi/notification/schemas.yml
  docs/api/openapi/notification/specification.yml
  docs/api/openapi/user/specification.yml
  docs/site/docs/report/02-ddd.md
  docs/spe-report/02-ddd.md
  docs/uml/domain/Anomaly.puml
  docs/uml/domain/Device.puml
  docs/uml/domain/DomainEvents.puml
  docs/uml/domain/Log.puml
  docs/uml/domain/Notification.puml
  docs/uml/domain/SecurityRule.puml
  docs/uml/domain/bounded-context/Alarm.puml
  docs/uml/domain/bounded-context/Auth.puml
  docs/uml/domain/bounded-context/Device-Monitoring.puml
  docs/uml/domain/bounded-context/User.puml
Labels: documentation

#115 ci(release): fix gha syntax
  .github/workflows/release.yml
Labels: bug, ci, autorebase-update

#177 ci: refactor
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: autorebase-update

#112 feat(frontend): introduce admin page
  auth/db/auth-init.js
  auth/package-lock.json
  auth/package.json
  auth/src/application/services/UserServiceImpl.ts
  auth/src/domain/core/User.ts
  auth/src/domain/factories/UserFactory.ts
  auth/src/infrastructure/api/routes/userPermission.ts
  auth/src/infrastructure/storage/MongoDBUserRepository.ts
  auth/src/infrastructure/storage/models/UserModel.ts
  auth/src/infrastructure/storage/schemas/UserSchema.ts
  auth/test/resources/userSample.ts
  auth/test/user/user.post.test.ts
  docs/api/openapi/auth/schemas.yml
  frontend/src/components/NavbarComponent.vue
  frontend/src/components/admin/ContactBadge.vue
  frontend/src/components/admin/NewContactPopup.vue
  frontend/src/components/admin/NewPermissionPopup.vue
  frontend/src/components/admin/PermissionBadge.vue
  frontend/src/components/admin/UserListElement.vue
  frontend/src/components/security-rule/NewRulePopup.vue
  frontend/src/domain/core/User.ts
  frontend/src/domain/core/UserRole.ts
  frontend/src/router/index.ts
  frontend/src/stores/user.ts
  frontend/src/views/AdminView.vue
  frontend/src/views/LocationsView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/UsersView.vue
  user/db/user-init.js
  user/package.json
  user/src/application/services/UserService.ts
  user/src/application/services/UserServiceImpl.ts
  user/src/infrastructure/api/controllers/user.ts
  user/src/infrastructure/api/routes/user.ts
  user/test/user/user.post.test.ts
Labels: frontend, refactor, automerge-update

#185 fix(ci): fix docker image publish step
  .github/workflows/build.yml
  alarm/Dockerfile
  auth/Dockerfile
  device/Dockerfile
  frontend/Dockerfile
  location/Dockerfile
  log/Dockerfile
  monitoring/Dockerfile
  notification/Dockerfile
  recognition/Dockerfile
  user/Dockerfile
Labels: autorebase-update

#189 docs(website): add job to build website
  .github/workflows/build.yml
  docs/website/.gitignore
  docs/website/babel.config.js
  docs/website/docs/intro.md
  docs/website/docs/report/01-requirements.md
  docs/website/docs/report/02-ddd.md
  docs/website/docs/report/03-architecture.md
  docs/website/docs/report/04-detailed-design.md
  docs/website/docs/report/05-implementation.md
  docs/website/docs/report/06-testing.md
  docs/website/docs/report/07-deployment.md
  docs/website/docs/report/08-conclusions.md
  docs/website/docs/report/_category_.json
  docs/website/docusaurus.config.ts
  docs/website/package-lock.json
  docs/website/package.json
  docs/website/sidebars.ts
  docs/website/src/pages/index.md
  docs/website/static/.nojekyll
  docs/website/static/img/docusaurus-social-card.jpg
  docs/website/static/img/docusaurus.png
  docs/website/static/img/favicon.ico
  docs/website/static/img/logo.svg
  docs/website/static/img/undraw_docusaurus_mountain.svg
  docs/website/static/img/undraw_docusaurus_react.svg
  docs/website/static/img/undraw_docusaurus_tree.svg
  docs/website/tsconfig.json
Labels: documentation, autorebase-update

#212 test: add general tests & align docs
  alarm/src/application/services/AlarmEventsHub.ts
  alarm/src/application/services/impl/AlarmServiceImpl.ts
  alarm/src/infrastructure/api/controllers/securityRulesController.ts
  alarm/src/infrastructure/api/routes/securityRulesRouter.ts
  alarm/src/infrastructure/events/KafkaAlarmEventsHub.ts
  alarm/src/presentation/SecurityRulePresenter.ts
  alarm/src/presentation/impl/SecurityRulePresenterImpl.ts
  alarm/src/presentation/schemas/SecurityRuleSchema.ts
  alarm/src/utils/JWTManager.ts
  auth/src/infrastructure/api/routes/userRegistry.ts
  common/src/infrastructure/events/KafkaConsumer.ts
  common/src/presentation/AnomalyPresenter.ts
  common/src/presentation/DevicePresenter.ts
  common/src/utils/JWTManager.ts
  device/src/application/services/impl/DeviceServiceImpl.ts
  device/src/index.ts
  device/src/infrastructure/api/routes/devices.ts
  device/src/infrastructure/events/KafkaDeviceEventsHub.ts
  docs/api/openapi/alarm/schemas.yml
  docs/api/openapi/alarm/specification.yml
  docs/api/openapi/auth/schemas.yml
  docs/api/openapi/auth/specification.yml
  docs/api/openapi/location/specification.yml
  docs/api/openapi/notification/specification.yml
  docs/api/openapi/user/specification.yml
  frontend/package-lock.json
  frontend/src/components/history/OutlierBadge.vue
  frontend/src/components/security-rule/UpdateRulePopup.vue
  frontend/src/views/HistoryView.vue
  frontend/src/views/HomeView.vue
  location/src/index.ts
  log/package-lock.json
  log/src/application/repositories/AnomalyRepository.ts
  log/src/application/services/AnomalyService.ts
  log/src/application/services/AnomalyServiceImpl.ts
  log/src/application/services/LogEventsHub.ts
  log/src/application/services/MeasurementServiceImpl.ts
  log/src/index.ts
  log/src/infrastructure/api/controller/anomalies.ts
  log/src/infrastructure/api/routes/anomalies.ts
  log/src/infrastructure/events/KafkaLogEventsHub.ts
  log/src/infrastructure/storage/MongoDBAnomalyRepository.ts
  log/src/infrastructure/storage/MongoDBMeasurementRepository.ts
  monitoring/package-lock.json
  monitoring/src/application/services/MonitoringEventsHub.ts
  monitoring/src/application/services/impl/MonitoringServiceImpl.ts
  monitoring/src/infrastructure/events/MonitoringEventsHubImpl.ts
  monitoring/src/infrastructure/events/kafka/KafkaMonitoringEventsHub.ts
  monitoring/src/infrastructure/events/socket/SocketMonitoringEventsHub.ts
  notification/src/application/services/impl/NotificationServiceImpl.ts
  notification/src/infrastructure/api/routes/notification.ts
  notification/src/infrastructure/events/kafka/KafkaNotificationEventsHub.ts
Labels: chore, refactor, autorebase-update

#207 docs(website): generate swagger UI pages
  .github/workflows/build.yml
  build.gradle.kts
  docs/website/docusaurus.config.ts
  src/resources/index.html
  src/resources/style.css
Labels: autorebase-update

#223 feat: add infrastructure components (traefik, prometheus, grafana) add one more broker and coordinator
  .env
  .gitignore
  LICENSE
  README.md
  alarm/docker-compose.yml
  auth/docker-compose.yml
  common/src/infrastructure/events/KafkaConsumer.ts
  deploy.sh
  device/docker-compose.yml
  frontend/docker-compose.yml
  gateway/docker-compose.yml
  gateway/traefik-values.yml
  kafka/docker-compose.yml
  location/docker-compose.yml
  log/docker-compose.yml
  monitoring/docker-compose.yml
  monitoring/src/index.ts
  notification/docker-compose.yml
  prometheus/docker-compose.yml
  prometheus/grafana-values.yml
  prometheus/grafana/dashboard.yml
  prometheus/grafana/dashboards/docker-dashboard.json
  prometheus/grafana/datasource.yml
  prometheus/prometheus-values.yml
  prometheus/prometheus.yml
  recognition/docker-compose.yml
  scripts/compose-all.sh
  scripts/compose.sh
  scripts/create-k8s-specifications.sh
  undeploy.sh
  user/docker-compose.yml
Labels: enhancement, automerge-update
