Repository revue-org/revue, pull requests merged in 2024-04, with the labels that each got.

#58 feature/mail-notification
  alarm/db/alarm-init.js
  alarm/package-lock.json
  alarm/src/consumer.ts
  auth/package-lock.json
  camera/package-lock.json
  domain/src/application/alarm-system/SecurityRuleService.ts
  domain/src/application/alarm-system/impl/SecurityRuleServiceImpl.ts
  domain/src/application/notification/MailService.ts
  domain/src/application/notification/NotificationService.ts
  domain/src/application/notification/impl/MailServiceImpl.ts
  domain/src/application/notification/impl/NotificationServiceImpl.ts
  domain/src/domain/monitoring/core/Contact.ts
  domain/src/domain/monitoring/core/impl/ContactImpl.ts
  domain/src/storage/monitoring/UserRepositoryImpl.ts
  frontend/package-lock.json
  log/package-lock.json
  monitoring/package-lock.json
  notification/package-lock.json
  notification/package.json
  notification/src/controller/notification.ts
  notification/src/init.ts
  notification/src/routes/notification.ts
  sensor/package-lock.json
Labels: enhancement

#60 Add tolerance tests
  .dockerignore
  .github/workflows/fault-tolerance-tests.yml
  alarm/package-lock.json
  alarm/package.json
  alarm/src/controller/recognizingNode.ts
  alarm/src/index.ts
  alarm/src/routes/recognizingNode.ts
  alarm/src/utils/KafkaManager.ts
  alarm/test/recognizingNode/recognizingNode.get.test.ts
  alarm/test/recognizingNode/recognizingNode.post.test.ts
  alarm/test/resources/recognizingNodeSample.ts
  alarm/test/storage/MongoDBMock.ts
  auth/package-lock.json
  auth/package.json
  camera/package-lock.json
  camera/package.json
  domain/package-lock.json
  domain/package.json
  fault-tolerance-tests.sh
  frontend/package-lock.json
  frontend/package.json
  log/package-lock.json
  log/package.json
  log/src/routes/environmentData.ts
  log/src/utils/KafkaManager.ts
  monitoring/Dockerfile
  monitoring/package-lock.json
  monitoring/package.json
  monitoring/src/utils/KafkaManager.ts
  monitoring/test/tolerance/tolerance.log.down.test.ts
  monitoring/test/tolerance/tolerance.sensor.down.test.ts
  monitoring/test/utils/RequestHelper.ts
  monitoring/vitest.config.mjs
  notification/docker-compose.yml
  notification/package-lock.json
  notification/package.json
  notification/src/utils/KafkaManager.ts
  package-lock.json
  package.json
  recognition/Dockerfile
  recognition/app/presentation/securityrule/IntrusionRuleSerializer.py
  recognition/run_tests.py
  sensor/docker-compose.yml
  sensor/package-lock.json
  sensor/package.json
  settings.gradle.kts
Labels: test, refactor

#65 token verification for frontend redirect
  frontend/src/main.ts
  frontend/src/utils/RequestHelper.ts
  frontend/src/views/HomeView.vue
Labels: chore

#68 ci: setup node for release
  .github/workflows/release.yml
Labels: ci

#66 Add get latest environment data by sensor in log service and display them in frontend
  domain/src/application/log/LogService.ts
  domain/src/application/log/impl/LogServiceImpl.ts
  domain/src/domain/device/repositories/EnvironmentDataRepository.ts
  domain/src/storage/device/EnvironmentDataRepositoryImpl.ts
  frontend/src/views/HomeView.vue
  log/src/consumer.ts
  log/src/controller/environmentData.ts
  log/src/controller/sensor.ts
  log/src/index.ts
  log/src/routes/environmentData.ts
  log/src/routes/sensor.ts
  log/src/utils/JWTManager.ts
Labels: enhancement, frontend

#67 Add initial report and some diagram
  docs/ds-report/main.tex
  docs/ds-report/out/main.pdf
  docs/ds-report/references.bib
  docs/uml/Activity.plantuml
  docs/uml/requirements/UseCase.plantuml
  docs/uml/system/CameraProducingSequence.puml
  docs/uml/system/DependencyGraph.puml
  docs/uml/system/Deployment.puml
  docs/uml/system/DeviceActivity.plantuml
  docs/uml/system/Microservice.puml
  docs/uml/system/RecognitionActivity.plantuml
  docs/uml/system/SensorProducingSequence.puml
Labels: documentation, test

#69 fix: docker network subnet and access from host
  .env
  media-server/docker-compose.yml
  scripts/compose-all.sh
  scripts/compose-db.sh
  scripts/compose-service.sh
Labels: fix

#70 Tolerance test for down notification service
  alarm/Dockerfile
  alarm/db/alarm-init.js
  alarm/package.json
  alarm/src/consumer.ts
  alarm/test/tolerance/tolerance.notification.down.test.ts
  alarm/vitest.config.mjs
  domain/src/application/alarm-system/impl/SecurityRuleServiceImpl.ts
  fault-tolerance-tests.sh
  monitoring/test/tolerance/tolerance.log.down.test.ts
Labels: test

#71 Fix camera stream on frontend and recognition service startup
  .gitignore
  alarm/db/alarm-init.js
  alarm/docker-compose.yml
  alarm/src/index.ts
  alarm/src/utils/JWTManager.ts
  auth/docker-compose.yml
  camera/docker-compose.yml
  docs/uml/domain/Alarm.puml
  domain/src/domain/device/core/impl/EnvironmentDataImpl.ts
  frontend/docker-compose.yml
  frontend/src/env.d.ts
  frontend/src/utils/RequestHelper.ts
  frontend/src/views/HistoryView.vue
  kafka/docker-compose.yml
  log/docker-compose.yml
  media-server/docker-compose.yml
  monitoring/docker-compose.yml
  notification/docker-compose.yml
  recognition/Dockerfile
  recognition/app/main.py
  recognition/app/utils/env.py
  recognition/docker-compose.yml
  recognition/poetry.lock
  recognition/poetry.toml
  recognition/pyproject.toml
  recognition/requirements.txt
  recognition/run_tests.py
  sensor/docker-compose.yml
Labels: enhancement, fix

#72 Add tolerance test for auth service
  domain/src/application/notification/impl/MailServiceImpl.ts
  fault-tolerance-tests.sh
  monitoring/test/tolerance/tolerance.log.down.test.ts
  monitoring/test/tolerance/tolerance.sensor.down.test.ts
  notification/Dockerfile
  notification/package.json
  notification/src/index.ts
  notification/test/tolerance/tolerance.auth.down.test.ts
  notification/vitest.config.mjs
Labels: test

#74 Update UML
  docs/uml/domain/Aggregates-full.puml
  docs/uml/domain/Aggregates.puml
  docs/uml/domain/Alarm.puml
  docs/uml/domain/Anomaly.puml
  docs/uml/domain/Log.puml
  docs/uml/domain/Monitoring.puml
  docs/uml/domain/Notification.puml
  docs/uml/domain/SecurityRule.puml
  docs/uml/domain/User.puml
  docs/uml/requirements/UseCase.plantuml
  domain/src/storage/notification/NotificationRepositoryImpl.d.ts
  domain/src/storage/notification/NotificationRepositoryImpl.js
  recognition/app/main.py
  recognition/app/recognizer/Recognizer.py
  recognition/app/utils/interval.py
Labels: documentation
